### PR TITLE
Got hematite working with glutin.

### PR DESCRIPTION
**Pull request by Geemili**
However, I couldn't get the camera working. Uncommenting the camera update line gives the error: "the trait bound `piston_window::Event: piston::input::GenericEvent` is not satisfied"

I still need to do some work, but some help on the error would be nice.

### CODE REVIEW

**Comment by bvssvni** [comment]
I think Glutin does not have relative mouse movement when capturing a cursor, so the camera doesn't work. I opened https://github.com/tomaka/glutin/issues/774.

**Comment by mattico** [comment]
All this needs to work is to update the pistoncore-glutin_window dependency to 0.26.1 to support the newly added mouserelative events.

**Comment by mattico** [comment]
After trying this locally, the glium version feels a bit weird with the mouse. I'm not sure if there's something with the mouserelative implementation or if the sensitivity is just crazy high.

**Comment by mattico** [comment]
It looks like the camera controller has no built-in way to control the mouse sensitivity, that's probably the best place to do it. It seems like good functionality to have anyway. I've opened an issue: https://github.com/PistonDevelopers/camera_controllers/issues/31

**Comment by mattico** [comment]
Thanks @Geemili!

**Comment by Geemili** [comment]
You're welcome! :)

**Pull request merged**
