### PR TITLE
README Update proposal

### PR DESCRIPTION
**Pull request by toqueteos**
[Pretty version](https://github.com/toqueteos/hematite/blob/update-readme/README.md)

### CODE REVIEW

**Comment by fenhl** [comment]
What happened to the `cargo build release` step?

**Comment by fenhl** [comment]
Fixes #176

**Comment by toqueteos** [comment]
I tried to unify requirements and instructions by OS, cargo run o cargo build works the same way in all places.

**Comment by fenhl** [comment]
Looks good, can we merge this?

**Comment by toqueteos** [comment]
@fenhl I'm ok with merging, I was expecting a bit more discussion about it :/

**Comment by fenhl** [comment]
The paths on Linux are as follows:

*   Minecraft folder: `~/.minecraft`
*   Worlds folder: `~/.minecraft/saves/<world>`

**Comment by bvssvni** [comment]
@fenhl I added it through https://github.com/PistonDevelopers/hematite/pull/188

**Pull request merged**
