### PR TITLE
Update to latest Rust (3ef8ff1f8 2015-02-12)

### PR DESCRIPTION
**Pull request by toqueteos**
`rustc 1.0.0-nightly (3ef8ff1f8 2015-02-12 00:38:24 +0000)`

`shaders!` macro got removed.

### CODE REVIEW

**Comment by bvssvni** [comment]
@toqueteos Did I messed it up? Remember to self merge small changes!

**Comment by toqueteos** [comment]
@bvssvni It's my fault, I did change things on a different branch but because of discussion didn't end up merging when resolved.

**Comment by toqueteos** [comment]
Ok... It seems we can't specify versioned shader sources now, which one should I keep? `glsl_120` or `glsl_150`.

**Comment by bvssvni** [comment]
See https://github.com/gfx-rs/gfx-rs/issues/552

**Comment by toqueteos** [comment]
Waiting for Travis OK.

It seems the approach for *"versioned shaders"* is gonna be through [kmcallister/glassful](https://github.com/kmcallister/glassful).

**Pull request merged**
