### PR TITLE
Upgrade to modern gfx-rs, using PSOs

### LINKED ISSUE #214: Upgrade for modern gfx-rs, using Stream/Canvas
Also, kill SDL2 usage in favor of Glutin and `gfx_window_glutin`, since we are at it.

cc @eddyb

### PR DESCRIPTION
**Pull request by mattico**
I've just started working on this (again) so it's not nearly done. I'm mostly just putting this up so that I don't forget about it again :)

~~Is there a reason to not use tilde/caret requirements in Cargo.toml? Cargo.lock is checked in so you still need to explicitly `cargo update` for anything to change.~~

Closes #214

### CODE REVIEW

**Comment by bvssvni** [comment]
Cargo interpretates "0.8.0" as "^0.8.0".

**Comment by mattico** [comment]
Wow, I feel like I would have figured that out by now.

**Comment by mattico** [comment]
That's all for today, I think it's mostly complete. Black screen for now, but it builds and there's no crashes.

**Comment by mattico** [comment]
It works! \o/

Except for this one triangle...
hematite

and mouselook. I think something changed in camera_controllers?

**Comment by mattico** [comment]
Fixed the missing triangle. I think the mouse problem is becaues glutin_window doesn't implement `MouseRelative`.

**Comment by mattico** [comment]
Also worth investigating: this version gets ~250fps while master gets ~500fps on my machine. Probably doing something wrong with the vbuffer or with encoder.reset()

**Comment by toqueteos** [comment]
Congrats @mattico! You are doing awesome work here :+1:

**Comment by mattico** [comment]
Alright, everything works now. Performance also seems to be better with the sdl2 window. I'll squash these commits before merging.

The changes seem pretty straightforward, but I'd like at least one other opinion before I pull the trigger.

**Comment by bvssvni** [comment]
Looks good!

**Comment by mattico** [comment]
Of course I remember this right after I hit the merge button...

Since we're still using SDL, I shouldn't remove the part of the README that has SDL stuff in it.

**Pull request merged**
