### PR TITLE
Switched to latest crates dependencies

### PR DESCRIPTION
**Pull request by kvark**
Requires https://github.com/PistonDevelopers/gfx_voxel/pull/51

### CODE REVIEW

**Comment by bvssvni** [comment]
:+1: Merging.

**Comment by kvark** [comment]
@bvssvni please publish gfx_voxel and add me to the owners.

**Comment by bvssvni** [comment]
@kvark Done.

**Comment by kvark** [comment]
@bvssvni thanks! And we are all green again \o/

**Pull request merged**
